"""add blogpost model

Revision ID: 62cfa7a9331c
Revises: 02263a2a70e0
Create Date: 2022-04-23 18:02:52.642742

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '62cfa7a9331c'
down_revision = '02263a2a70e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=128), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_post_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_post'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    # ### end Alembic commands ###
