name: CI workflows

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  code-quality:
    name: Python code quality checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check formatting
        run: |
          black --check splendidsuns/ tests/
          isort --check-only splendidsuns/ tests/

      - name: Check for error and style violations
        run: |
          flake8 splendidsuns/ tests/

      - name: Check typing
        run: |
          mypy splendidsuns/ tests/

      - name: Run unit tests
        run: |
          pytest --cov splendidsuns --cov-report html --cov-fail-under 90 tests/ -v
